// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOZ8HDMSC7GBqWY0-U1Pyw8EP-WhsWa8',
    appId: '1:26908650629:web:08ac8c6cfdd627c7808dec',
    messagingSenderId: '26908650629',
    projectId: 'event-creation-4b956',
    authDomain: 'event-creation-4b956.firebaseapp.com',
    storageBucket: 'event-creation-4b956.firebasestorage.app',
    measurementId: 'G-SF8H8HGHBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3BFTjAnsgh7ZhKlPmoNynE66IMI-xg4',
    appId: '1:26908650629:android:a40a4a46316be9cb808dec',
    messagingSenderId: '26908650629',
    projectId: 'event-creation-4b956',
    storageBucket: 'event-creation-4b956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXyB2BCpgX-3wrTivI2JJy9RWNEmMrfUw',
    appId: '1:26908650629:ios:b9747f8594e2ab42808dec',
    messagingSenderId: '26908650629',
    projectId: 'event-creation-4b956',
    storageBucket: 'event-creation-4b956.firebasestorage.app',
    iosBundleId: 'com.example.eventCreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXyB2BCpgX-3wrTivI2JJy9RWNEmMrfUw',
    appId: '1:26908650629:ios:b9747f8594e2ab42808dec',
    messagingSenderId: '26908650629',
    projectId: 'event-creation-4b956',
    storageBucket: 'event-creation-4b956.firebasestorage.app',
    iosBundleId: 'com.example.eventCreation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOZ8HDMSC7GBqWY0-U1Pyw8EP-WhsWa8',
    appId: '1:26908650629:web:ed7aa06ed8fc4b79808dec',
    messagingSenderId: '26908650629',
    projectId: 'event-creation-4b956',
    authDomain: 'event-creation-4b956.firebaseapp.com',
    storageBucket: 'event-creation-4b956.firebasestorage.app',
    measurementId: 'G-ZVHQ84BMHC',
  );
}
